### ISSUE TITLE
Rename.fsx - Does not transform all projects

### ISSUE THREAD

**Issue by bo-stig-christensen** [delegateas/XrmFramework#10]
Rename.fsx transforms only Plugins and Workflows projects.
Other projects are still based on "XrmFramework" namespaces and assembly names.

Rename.fsx should transform all projects.

**Comment by pksorensen** [comment]
I could not get it to work, @thygesteffensen  told me to run it twice :)

**Comment by ntinggaard** [comment]
The WebResources src folder is not renamed either.

**Comment by san-86** [comment]
It does not work because the path for the fsianycpu.exe have been moved to another folder
it is now in  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools" at least for VS2019 have not checked the other versions

**Comment by misoeli** [comment]
It doesn't have anything to do with the FSI path, as the script does execute. If I understand @bo-stig-christensen the issue is that some projects in the solution are still in the namespace DG.XrmFramework (eg. businessdomain, businesslogic)
The rename has only been targeting DG.XrmOrg.XrmSolution so far, meaning it has never been the intention to rename the other projects of the solution.
